#! /usr/bin/env python3

"""
# Simple wrapper for the ways we use LLMs.

It is used as follows:

    import tools

    ai = tools.LLM(purpose='dummy')
    stream = ai.query('What is a parrot?')
    print(stream.response())

LLM(purpose='general') constructor:

  - purpose (str, default: 'general')
    Our intended use of the LLM. See purposes.py for supported values.
    The idea is for this purpose to determine a series of configuration
    parameters such as:
    - which LLM model and provider is chosen
    - optionally, a system prompt
    - a limit on the number of generated tokens
    - temperature and other inference parameters

LLM.query(user_query):

  - user_query (either str or iterable)
    - str: the LLM prompt
    - iterable: a sequence of
          { 'role': <role>, 'content': <content> }
      dictionaries with two entries:
      - 'role': string, one of 'system', 'user' or 'assistant'
      - 'content': the corresponding system prompt, user prompt, or LLM
        response, respectively
      Passing an iterable user_query enables a conversation mode in which
      the LLM knows of previous user prompts and of its own previous
      responses.

  Return value: a Stream object. This object has two relevant methods:

  - Stream.response() waits for the complete LLM response and returns it
    as a string.

  - Stream.chunks() returns an iterable which allows us to stream response
    tokens (strings) as they are generated by the LLM.

  See purposes.py for details. Under the hood, all arguments passed to
  llm.LLM.query() are simply forwarded to the constructor of this Stream
  class.

# Purposes for LLM uses.

Currently supported values:

- 'dummy': a trivial test config that just returns the prompt as a response
- 'general': a general-purpose config, currently using OpenAI as the
  default provider (see the 'defaults' entry in the configs dict below).
  Other providers ('anthropic', 'gemini', 'fireworks', 'hyperbolic') can
  be selected with LLM(purpose='anthropic') or
  ai.override({'include': ['anthropic']}).

The config field is a dictionary of configuration parameters.

One can override individual parameters after LLM() construction as follows:

    ai = tools.LLM(purpose = 'general')
    ai.config['model_shortcut'] = 'fast'

A particular entry in this dictionary has the key 'query_streamer'.
The corresponding value is a class derived from Stream. An instance
of this class is created in and returned by LLM.query(). Parameters to
LLM.query() are forwarded to the constructor.

# Embeddings

Embedding vectors can be computed as follows:

    ai = tools.llm.LLM(purpose='embed')
    vector = ai.embed(text).vector()

where text is a string, and we obtain the vector as list of floats.

"""
import os
import sys
import time
import argparse
import re
import openai

# ****************************************************************************
# Stream parent class
# ****************************************************************************
class Stream:
    def __init__(self, *args, **kwargs):
        raise NotImplementedError

    def chunks(self, *args, **kwargs):
        raise NotImplementedError

    def response(self, dump=None):
        r = ''

        for chunk in self.chunks():
            if dump:
                dump.write(chunk)
                dump.flush()

            r += chunk

        if dump:
            dump.write(f'\n\ntokens: {self.prompt_tokens}'
                + f' + {self.completion_tokens}\n\n')

        return r

# ****************************************************************************
# Dummy stream
# ****************************************************************************
class DummyStream(Stream):
    def __init__(self, cfg, user_query, system_prompt = None):
        s = ''

        if system_prompt:
            s += system_prompt + '\n\n'

        if type(user_query) is str:
            s += user_query
        else:
            q = ''
            for msg in user_query:
                if msg['role'] == 'system':
                    s += msg['content'] + '\n\n'
                elif msg['role'] == 'user':
                    q = msg['content']
            s += q

        self.echo = re.findall(r'\w+|.|\n', s)
        self.prompt_tokens = 0
        self.completion_tokens = 0
        self.total_tokens = 0

        self.delay = cfg['token_delay'] if 'token_delay' in cfg else 0.02

    def chunks(self):
        for r in self.echo:
            time.sleep(self.delay)
            yield r

# ****************************************************************************
# Chat Completion stream
# ****************************************************************************
# ****************************************************************************
# API key resolution
# ****************************************************************************
def api_key(cfg):
    """Resolve a provider's API key.

    Keys are read from the environment at call time (not at import time),
    so loading a .env file after importing this module still works.
    An explicit cfg['api_key'] takes precedence if one is set.
    """
    key = cfg.get('api_key') or os.environ.get(cfg.get('api_key_env', ''))
    if not key:
        raise ValueError(
            f'No API key for the provider at {cfg.get("base_url")}. '
            f'Set {cfg.get("api_key_env", "the provider key")} in .env and '
            'load it (run_pipeline.py does this automatically; for manual '
            'runs: set -a; source .env; set +a).')
    return key


class CompletionStream(Stream):
    def __init__(self, cfg, user_query, system_prompt=None):
        # Reasoning models emit thinking tokens before the answer and can
        # leave the stream idle for a long time between chunks, which the
        # SDK's default read timeout treats as a dead connection. A generous
        # timeout plus a few retries turns that into a slow run rather than a
        # failed batch. Override per provider with cfg['timeout'] /
        # cfg['max_retries'] if one of them needs different limits.
        client = openai.OpenAI(
            base_url=cfg['base_url'],
            api_key=api_key(cfg),
            timeout=cfg.get('timeout', 600.0),
            max_retries=cfg.get('max_retries', 3),
        )

        msg = []

        if 'system_prompt' in cfg:
            msg.append({ 'role': 'system', 'content': cfg['system_prompt'] })

        if system_prompt:
            msg.append({ 'role': 'system', 'content': system_prompt })

        if type(user_query) is str:
            msg.append({ 'role': 'user', 'content': user_query })
        else:
            for m in user_query:
                msg.append(m)

        if 'model' in cfg:
            model = cfg['model']
        elif 'model_shortcut' in cfg:
            shortcut = cfg['model_shortcut']
            model = cfg['model_shortcuts'][shortcut]
        else:
            raise ValueError('model not specified in configuration')

        params = { 'stream': True, 'model': model, 'messages': msg }

        # 'reasoning_effort' is forwarded so that a provider config can turn
        # thinking off (see 'fireworks' below). It is only ever sent when a
        # config sets it, so providers that do not accept the parameter are
        # unaffected.
        direct_copy = { 'temperature', 'top_p', 'top_k', 'n', 'max_tokens',
                        'stop', 'presence_penalty', 'frequency_penalty',
                        'reasoning_effort' }

        for key in cfg:
            if key in direct_copy:
                params[key] = cfg[key]

        self.stream = client.chat.completions.create(**params)

        self.prompt_tokens = 0
        self.completion_tokens = 0
        self.total_tokens = 0

    def chunks(self):
        for chunk in self.stream:
            # Providers differ here: Fireworks sends a final usage-only
            # chunk with an empty choices list, and reasoning models send
            # chunks whose delta has no visible content. Both are normal.
            if chunk.choices:
                s = chunk.choices[0].delta.content

                if s is not None:
                    yield s

            usage = getattr(chunk, 'usage', None)
            if usage:
                self.prompt_tokens = usage.prompt_tokens
                self.completion_tokens = usage.completion_tokens
                self.total_tokens = usage.total_tokens


# ****************************************************************************
# Embedders
# ****************************************************************************
class Embedder:
    def __init__(self, *args, **kwargs):
        raise NotImplementedError

    def vector(self, *args, **kwargs):
        raise NotImplementedError

class DummyEmbedder(Embedder):
    def __init__(self, cfg, text):
        self.prompt_tokens = 0
        self.total_tokens = 0

    def vector(self):
        return [ 1.0, 0.0, 0.0 ]

class EmbeddingsEmbedder(Embedder):
    def __init__(self, cfg, text):
        client = openai.OpenAI(
            base_url=cfg['base_url'],
            api_key=api_key(cfg),
        )

        if 'embedding_model' in cfg:
            model = cfg['embedding_model']
        elif 'embedding_shortcut' in cfg:
            shortcut = cfg['embedding_shortcut']
            model = cfg['embedding_shortcuts'][shortcut]
        else:
            raise ValueError('embedding model not specified in configuration')

        params = { 'model': model, 'input': text, 'timeout': 5.0 }

        self.response = client.embeddings.create(**params)

        self.prompt_tokens = self.response.usage.prompt_tokens
        self.total_tokens = self.response.usage.total_tokens

    def vector(self):
        return self.response.data[0].embedding

# ****************************************************************************
# General-purpose LLM configuration
# ****************************************************************************
configs = {

'defaults': {
    'query_streamer': CompletionStream,
    'model_shortcut': 'small',
    #'system_prompt': '',
    #'temperature': 0.7,
    'max_tokens': 2048,

    'embedder': EmbeddingsEmbedder,
    'embedding_shortcut': 'small',

    # Default chat provider. OpenAI is used by default because its
    # non-reasoning chat models (gpt-4o via the 'medium' shortcut) return
    # the bare list the selection prompt asks for, which keeps parsing
    # simple. Override per run with --provider.
    'include': [ 'openai' ],
},

'general': {
},

'dummy': {
    'query_streamer': DummyStream,
    'embedder': DummyEmbedder,
},

'generate': {
    'model_shortcut': 'medium',
    'max_tokens': 8000,
},

'summarize': {
    'model_shortcut': 'medium',
    'max_tokens': 12000,
    #'temperature': 0.1,
},

'embed': {
    'include': [ 'openai' ],
},

'hyperbolic': {
    'api_key_env': 'HYPERBOLIC_API_KEY',
    'base_url': 'https://api.hyperbolic.xyz/v1',
    'model_shortcuts': {
        'fast':     'meta-llama/Llama-3.2-3B-Instruct',         # $0.10 / M
        'small':    'meta-llama/Meta-Llama-3.1-8B-Instruct',    # $0.10 / M
        'medium':   'meta-llama/Llama-3.3-70B-Instruct',        # $0.40 / M
        'large':    'meta-llama/Meta-Llama-3.1-405B-Instruct',  # $4.00 / M
        'old':      'meta-llama/Meta-Llama-3-70B-Instruct',     # $0.40 / M
    },
},

'openai': {
    'api_key_env': 'OPENAI_API_KEY',
    'base_url': 'https://api.openai.com/v1',
    'model_shortcuts': {
        'fast':     'gpt-4o-mini',
        'small':    'gpt-4o-mini',
        'medium':   'gpt-4o',
        'large':    'gpt-4.1',
        'gpt4o':    'gpt-4o',
        'gpt41':    'gpt-4.1',
        'gpt41mini': 'gpt-4.1-mini',
    },
    'embedding_shortcuts': {
        'small':    'text-embedding-3-small',  # dim 1536
    },
},


'fireworks': {
    'api_key_env': 'FIREWORKS_API_KEY',
    'base_url': 'https://api.fireworks.ai/inference/v1',
    'max_tokens': 64000,
    # GLM-5p2 and Kimi K3 spend their whole budget on thinking tokens before
    # answering, so even at 64000 the reply was still being truncated before
    # the chunk list appeared. Disabling reasoning makes them answer directly.
    # NOTE: this applies to every Fireworks model, so a re-run of qwen would
    # no longer match the 100 runs already recorded for it.
#     'reasoning_effort': 'none',
    'model_shortcuts': {
        'fast':     'accounts/fireworks/models/gpt-oss-120b',
        'small':    'accounts/fireworks/models/gpt-oss-120b',
        'medium':   'accounts/fireworks/models/glm-5p2',
        'large':    'accounts/fireworks/models/deepseek-v4-pro',
        # explicit names, for the cross-model study
        'gpt-oss':  'accounts/fireworks/models/gpt-oss-120b',
        'glm':      'accounts/fireworks/models/glm-5p2',
        'glm51':    'accounts/fireworks/models/glm-5p1',
        'kimi':     'accounts/fireworks/models/kimi-k2p6',
        'deepseek': 'accounts/fireworks/models/deepseek-v4-pro',
        'kimi3':    'accounts/fireworks/models/kimi-k3',
        'qwen':     'accounts/fireworks/models/qwen3p7-plus',
        'qwen38':   'accounts/fireworks/models/qwen3p8-max',
    },
},

'gemini': {
    'api_key_env': 'GEMINI_API_KEY',
    'base_url': 'https://generativelanguage.googleapis.com/v1beta/openai/',
    'model_shortcuts': {
        'fast':      'gemini-3.1-flash-lite',
        'small':     'gemini-3.1-flash-lite',
        'medium':    'gemini-3.5-flash',
        'large':     'gemini-3.1-pro-preview',
        'flash36':   'gemini-3.6-flash',
        'flashlite': 'gemini-3.1-flash-lite',
    },
},

'anthropic': {
    'api_key_env': 'ANTHROPIC_API_KEY',
    'base_url': 'https://api.anthropic.com/v1/',
    'model_shortcuts': {
        'fast':   'claude-haiku-4-5-20251001',
        'small':  'claude-haiku-4-5-20251001',
        'medium': 'claude-sonnet-4-5',
        'large':  'claude-opus-4-5',
        'haiku':  'claude-haiku-4-5-20251001',
        'sonnet': 'claude-sonnet-4-5',
        'opus':   'claude-opus-4-5',
    },
},

}

# Providers usable as chat backends (i.e. selectable via purpose/include).
PROVIDERS = [ 'openai', 'anthropic', 'gemini', 'fireworks', 'hyperbolic' ]

_hyperbolic_models = [
'meta-llama/Llama-3.3-70B-Instruct',
'meta-llama/Llama-3.2-3B-Instruct',
'meta-llama/Meta-Llama-3.1-8B-Instruct',
'meta-llama/Meta-Llama-3.1-70B-Instruct',
'meta-llama/Meta-Llama-3.1-405B-Instruct',
'meta-llama/Meta-Llama-3.1-405B',
'meta-llama/Meta-Llama-3-70B-Instruct',
'NousResearch/Hermes-3-Llama-3.1-70B',
'Qwen/Qwen2.5-72B-Instruct',
'FLUX.1-dev',
'mistralai/Pixtral-12B-2409',
'StableDiffusion',
'Qwen/Qwen2-VL-72B-Instruct',
'TTS',
'Qwen/Qwen2-VL-7B-Instruct',
'deepseek-ai/DeepSeek-V2.5',
]

# https://docs.hyperbolic.xyz/reference/create_chat_completion_v1_chat_completions_post
_hyperbolic_params_doc = '''

- messages (array of objects, required)
  A list of messages comprising the conversation.
  - object
    - role (string, Defaults to user)
      The role of the messages author.
      Choice between: system, user, or assistant.
    - content (string Defaults to what is GPU?)
      The contents of the message.
- temperature (Defaults to 0.7)
  A decimal number that determines the degree of randomness in the response.
  A value of 1 will always yield the same output. A temperature less than 1
  favors more correctness and is appropriate for question answering or
  summarization. A value greater than 1 introduces more randomness in the
  output.

- top_p (Defaults to 1)
  The top_p (nucleus) parameter is used to dynamically adjust the number of
  choices for each predicted token based on the cumulative probabilities. It
  specifies a probability threshold, below which all less likely tokens are
  filtered out. This technique helps to maintain diversity and generate more
  fluent and natural-sounding text.

- top_k (Defaults to -1)
  The top_k parameter is used to limit the number of choices for the next
  predicted word or token. It specifies the maximum number of tokens to
  consider at each step, based on their probability of occurrence. This
  technique helps to speed up the generation process and can improve the
  quality of the generated text by focusing on the most likely options.

- n (Defaults to 1)
  How many completions to generate for each prompt.

- max_tokens
  The maximum number of tokens to generate.

- stop
  A list of string sequences that will truncate (stop) inference text output.
  For example, will stop generation as soon as the model generates the given
  token.

- stream (Defaults to false)
  Whether to stream the response back to the client. If true, stream tokens as
  Server-Sent Events as the model generates them instead of waiting for the
  full model response. If false, return a single JSON object containing the
  results.

- presence_penalty (Defaults to 0)
  Number between -2.0 and 2.0. Positive values penalize new tokens based on
  whether they appear in the text so far, increasing the model's likelihood
  to talk about new topics.

- frequency_penalty (Defaults to 0)
  Number between -2.0 and 2.0. Positive values penalize new tokens based on
  their existing frequency in the text so far, decreasing the model's
  likelihood to repeat the same line verbatim..

- user
  A unique identifier representing end-user.

'''

# ****************************************************************************
# Entry point
# ****************************************************************************
class LLM:
    def __init__(self, purpose='general'):
        self.config = {}
        self.override({ 'include': [ 'defaults' ] })
        if type(purpose) is str:
            self.override({ 'include': purpose.split() })

    def override(self, cfg):
        for key in cfg:
            if key == 'include':
                for purpose in cfg['include']:
                    if purpose not in configs:
                        raise ValueError(f'Unknown purpose "{purpose}". '
                            f'Known: {", ".join(sorted(configs))}')
                    self.override(configs[purpose])
            else:
                self.config[key] = cfg[key]

    def query(self, *args, **kwargs):
        streamer = self.config['query_streamer']
        return streamer(self.config, *args, **kwargs)

    def embed(self, *args, **kwargs):
        embedder = self.config['embedder']
        return embedder(self.config, *args, **kwargs)

class MessageBuilder:
    def __init__(self, options = None):
        self.options = options or {}

    def generic(self, role, content):
        return { 'role': role, 'content': content }

    def system(self, content):
        return self.generic('system', content)

    def user(self, content):
        return self.generic('user', content)

    def assistant(self, content):
        return self.generic('assistant', content)

# ****************************************************************************
# Tests
# ****************************************************************************
def llm_tests():
    # Command-line arguments
    ap = argparse.ArgumentParser()
    ap.add_argument('-s', '--sys', help='System prompt')
    ap.add_argument('-S', '--sys-file', help='System prompt file')
    ap.add_argument('-u', '--user', help='User prompt')
    ap.add_argument('-U', '--user-file', help='User prompt file')
    ap.add_argument('-i', '--interactive', help='Force interactive mode', action='store_true')
    ap.add_argument('--no-history', help='Disable conversation history', action='store_true')
    args = ap.parse_args()

    sys_prompt = None

    if args.sys is not None:
        sys_prompt = args.sys
    elif args.sys_file == '-' and args.user_file != '-':
        sys_prompt = sys.stdin.read()
    elif args.sys_file is not None:
        with open(args.sys_file) as f:
            sys_prompt = f.read()

    user_prompt = None

    if args.user is not None:
        user_prompt = args.user
    elif args.user_file == '-':
        user_prompt = sys.stdin.read()
    elif args.user_file is not None:
        with open(args.user_file) as f:
            user_prompt = f.read()

    interactive = False

    if sys_prompt is None and user_prompt is None:
        interactive = True
    elif args.interactive:
        interactive = True

    conversation = not args.no_history

    if sys_prompt is None:
        if interactive and args.sys_file != '-' and args.user_file != '-':
            try:
                sys_prompt = input('\x1b[94msystem: \x1b[0m')
            except EOFError:
                pass
            except KeyboardInterrupt:
                exit(0)

    # LLM
    #ai = LLM(purpose='dummy')
    ai = LLM()
    #ai.config['model_shortcut'] = 'medium'
    ai.config['max_tokens'] = 16384

    query = []

    while True:
        if not conversation:
            query = []

        if len(query) == 0 and sys_prompt is not None:
            query.append({ 'role': 'system', 'content': sys_prompt })
            history = []

        if user_prompt is not None:
            query.append({ 'role': 'user', 'content': user_prompt })
            user_prompt = None
        elif not interactive:
            break
        else:
            try:
                user_query = input('\x1b[92muser: \x1b[0m')
            except EOFError:
                break
            except KeyboardInterrupt:
                break

            if user_query == '':
                break

            query.append({ 'role': 'user', 'content': user_query })

        stream = ai.query(query)

        print()

        response = ''

        for chunk in stream.chunks():
            response += chunk
            print(chunk, flush = True, end = '')

        print(f'\n\n\x1b[90mprompt: {stream.prompt_tokens:5d}, '
            + f'completion: {stream.completion_tokens:5d}, '
            + f'total: {stream.total_tokens:5d}\x1b[0m\n', flush = True)

        query.append({ 'role': 'assistant', 'content': response })

    print('\n')


# ****************************************************************************
# Main
# ****************************************************************************
if __name__ == '__main__':
    llm_tests()
